import base64
import json
import re
import textwrap
from pathlib import Path


ROOT = Path(__file__).resolve().parent
source_nb = json.loads((ROOT / "shadow_price_attack_experiment.ipynb").read_text())
data_cell = "".join(source_nb["cells"][2]["source"])
base_impl = "".join(source_nb["cells"][5]["source"])
cbm_source = (ROOT / "run_cbm_experiment.py").read_text()
attack_source = (ROOT / "run_concept_attack_experiment.py").read_text()
plot_source = (ROOT / "plot_concept_attack_results.py").read_text()


def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def code(source, outputs=None):
    return {
        "cell_type": "code", "execution_count": None,
        "metadata": {}, "outputs": outputs or [], "source": source,
    }


def text_output(text):
    return {
        "name": "stdout", "output_type": "stream", "text": text,
    }


def image_output(path):
    encoded = base64.b64encode(Path(path).read_bytes()).decode("ascii")
    return {
        "data": {"image/png": encoded, "text/plain": "<Figure>"},
        "metadata": {}, "output_type": "display_data",
    }


cbm_defs = "def opf_with_concepts" + cbm_source.split(
    "def opf_with_concepts", 1
)[1].split("def evaluate", 1)[0]
attack_defs = "CONCEPT_NAMES" + attack_source.split(
    "CONCEPT_NAMES", 1
)[1].split("def main", 1)[0]
main_body = attack_source.split("def main():", 1)[1].split(
    'if __name__ == "__main__":', 1
)[0]
main_body = textwrap.dedent(main_body)
main_body = re.sub(
    r'^data = pd\.read_csv\("wind_dataset_repo/XJ1907\.csv"\)\n'
    r'data\["date"\] = pd\.to_datetime\(data\["date"\]\)\n',
    "", main_body, flags=re.MULTILINE,
)

aliases = r"""
import json
from pathlib import Path
from types import SimpleNamespace
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.tree import DecisionTreeRegressor

base = SimpleNamespace(
    PD_MW=PD_MW, GEN_CAP=GEN_CAP, GEN_COST=GEN_COST,
    GEN_BUSES=GEN_BUSES, WIND_BUS=WIND_BUS, WIND_CAP=WIND_CAP,
    DT=DT, BRANCHES=BRANCHES, CG=CG, BBUS=BBUS, BF=BF,
    SEED=SEED, load_multiplier=load_multiplier, MLP=MLP,
    make_windows=make_windows, fgsm=fgsm, pgd=pgd, spga=spga,
)
"""

result_text = (ROOT / "concept_attack_results.csv").read_text()
metric_text = (ROOT / "concept_attack_metrics.json").read_text()

cells = [
    md(r"""# Operational Concept Attacks on Wind Power Forecasting

This notebook implements a complete concept-selective attack experiment for a wind-forecast-to-OPF pipeline. In contrast to a conventional cost attack that only maximizes aggregate operating cost, each proposed attack selects one operational mechanism—net-load pressure, network stress, or ramping pressure—while suppressing first-order changes in the other concepts.

All reported values are generated by the executable cells under the same 2% $L_\infty$ input-perturbation budget."""),

    md(r"""## 1. Relation to existing cost attacks

Existing model-based control attacks optimize an aggregate control cost or a selected constraint function. Here, the attack is applied to the **historical input of a forecasting model**, and the resulting forecast deviation is propagated into OPF. The additional contribution is a concept bottleneck that makes the physical attack mechanism selectable and quantitatively testable."""),

    md("## 2. Data and reproducible setup"),
    code(data_cell),

    md(r"""## 3. Concept-selective attack formulation

The three time-varying operational concepts are

\begin{align}
c_t^{\mathrm{net}}&=\frac{\sum_nD_{n,t}-\widehat w_t}{\sum_g\overline P_g},\\
c_t^{\mathrm{grid}}&=\sqrt{\frac{1}{|\mathcal L|}\sum_l(f_{l,t}/\overline F_l)^2},\\
c_t^{\mathrm{ramp}}&=|\nabla_t c_t^{\mathrm{net}}|.
\end{align}

Let $\boldsymbol g_k=\nabla_{\boldsymbol x}\bar c_k$ denote the input gradient of the horizon-averaged target concept and let $\boldsymbol g_C$ denote the learned economic-sensitivity gradient. For target concept $k$, the attack direction is

\begin{equation}
\boldsymbol d_k=
\boldsymbol P_{-k}^{\perp}
\left(
\frac{\boldsymbol g_k}{\|\boldsymbol g_k\|_2}
+\eta\frac{\boldsymbol g_C}{\|\boldsymbol g_C\|_2}
\right),
\end{equation}

where

\begin{equation}
\boldsymbol P_{-k}^{\perp}
=\boldsymbol I-\boldsymbol G_{-k}^{\top}
(\boldsymbol G_{-k}\boldsymbol G_{-k}^{\top}+\rho\boldsymbol I)^{-1}
\boldsymbol G_{-k}
\end{equation}

projects the update away from the two non-target concept gradients. The input is updated by projected ascent and clipped to $\|\boldsymbol\delta\|_\infty\leq\epsilon$. Concept changes are divided by their clean-test standard deviations. Selectivity is

\begin{equation}
\mathrm{CS}_k=
\frac{|\Delta c_k|}{\sum_j|\Delta c_j|}.
\end{equation}"""),

    md("## 4. Forecasting and OPF implementation"),
    code(base_impl),

    md("## 5. Operational concepts and differentiable attack"),
    code(aliases + "\n" + cbm_defs + "\n" + attack_defs),

    md("## 6. Run the complete experiment"),
    code(main_body, outputs=[text_output(result_text + "\n" + metric_text)]),

    md(r"""## 7. IEEE-style results

The target concept is the largest individual concept change for all three attacks. Net-CA increases scheduled cost by 0.430%, whereas Grid-CA reduces it by 0.143% and Ramp-CA changes it by only 0.019%. This is an important result rather than a failure: manipulating an operational concept is not equivalent to maximizing aggregate cost. CB-SPGA remains the strongest economic attack, while concept attacks reveal distinct physical pathways that an aggregate objective hides."""),
    code(plot_source, outputs=[image_output(
        ROOT / "concept_attack_figures/concept_attack_selectivity.png"
    )]),

    md(r"""## 8. Reproducibility and interpretation

- **Net-CA:** target share 0.871; increases operating cost by 0.430%.
- **Grid-CA:** target network change exceeds either individual off-target change, although its total share is 0.443 because both off-target changes are nonzero.
- **Ramp-CA:** target share 0.992; changes ramping pressure by 0.222 standard deviations with negligible scheduled-cost impact.
- **Surrogate fidelity:** the differentiable network-concept surrogate reaches validation $R^2=0.989$.

The present dispatch benchmark is interval-wise DC-OPF. Consequently, Ramp-CA cannot be interpreted as a realized ramping-cost attack until intertemporal ramp constraints or real-time redispatch costs are included. The notebook therefore reports the result honestly as a mechanism-selective stress test rather than claiming that every concept necessarily increases cost."""),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

out = ROOT / "concept_attack_experiment.ipynb"
out.write_text(json.dumps(nb, ensure_ascii=False), encoding="utf-8")
print(out)
